server.port=8080
spring.application.name=sales-service

# ==========================================
# 1. Configuração do Kafka (Mensageria)
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=sales-group
spring.kafka.consumer.auto-offset-reset=earliest

# ==========================================
# 2. Configuração do Circuit Breaker (Resilience4j)
# ==========================================
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50

resilience4j.circuitbreaker.instances.paymentGateway.baseConfig=default